name: Validate Paper

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: impact-scholars/isp-actions-config/.github/workflows/validate-paper.yml@v0.1.0
